name: main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches-ignore:
      - main

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    name: update-mirror
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            curl

      - name: Download
        run: |
          mkdir -p dir/prod
          curl --fail "https://dgc-trust.qr.gv.at/trustlist" -o dir/prod/trustlist || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/prod/trustlist -o dir/prod/trustlist
          curl --fail "https://dgc-trust.qr.gv.at/trustlistsig" -o dir/prod/trustlistsig || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/prod/trustlistsig -o dir/prod/trustlistsig
          curl --fail "https://dgc-trust.qr.gv.at/rules" -o dir/prod/rules || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/prod/rules -o dir/prod/rules
          curl --fail "https://dgc-trust.qr.gv.at/rulessig" -o dir/prod/rulessig || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/prod/rulessig -o dir/prod/rulessig
          curl --fail "https://dgc-trust.qr.gv.at/valuesets" -o dir/prod/valuesets || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/prod/valuesets -o dir/prod/valuesets
          curl --fail "https://dgc-trust.qr.gv.at/valuesetssig" -o dir/prod/valuesetssig || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/prod/valuesetssig -o dir/prod/valuesetssig
          mkdir -p dir/test
          curl --fail "https://dgc-trusttest.qr.gv.at/trustlist" -o dir/test/trustlist || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/test/trustlist -o dir/test/trustlist
          curl --fail "https://dgc-trusttest.qr.gv.at/trustlistsig" -o dir/test/trustlistsig || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/test/trustlistsig -o dir/test/trustlistsig
          curl --fail "https://dgc-trusttest.qr.gv.at/rules" -o dir/test/rules || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/test/rules -o dir/test/rules
          curl --fail "https://dgc-trusttest.qr.gv.at/rulessig" -o dir/test/rulessig || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/test/rulessig -o dir/test/rulessig
          curl --fail "https://dgc-trusttest.qr.gv.at/valuesets" -o dir/test/valuesets || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/test/valuesets -o dir/test/valuesets
          curl --fail "https://dgc-trusttest.qr.gv.at/valuesetssig" -o dir/test/valuesetssig || curl --fail https://digital-blueprint.github.io/dgc-trust-mirror/test/valuesetssig -o dir/test/valuesetssig
          cp README.md ./dir
          cp index.html ./dir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dir
          publish_branch: main